### ISSUE TITLE
缺失customData 导致请求终止

### ISSUE THREAD

**Issue by 0xRainzy** [kviewui/lwu-request#22]
版本 1.8.3

hbuilderx：4.24

Vue3

平台：App

![image](https://github.com/user-attachments/assets/d40f9322-668e-4756-bd4e-b2571aae9e0a)

**Comment by Jazzzy126** [comment]
怎么解决的

**Comment by 0xRainzy** [comment]
> 怎么解决的

客户给的域名不对

**Comment by Jazzzy126** [comment]
> > 怎么解决的
> 
> 客户给的域名不对

我这边域名是对的，感觉跟你的错误差不多
![Uploading image.png…]()

**Comment by 0xRainzy** [comment]
看不到你发的图片 @Jazzzy126

**Comment by Jazzzy126** [comment]
![image](https://github.com/user-attachments/assets/aced6fbd-0ac4-43e3-9b5c-0e60667aae32)

**Comment by 0xRainzy** [comment]
> ![image](https://private-user-images.githubusercontent.com/61782856/357738886-aced6fbd-0ac4-43e3-9b5c-0e60667aae32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjQ4MDksIm5iZiI6MTcyMzYyNDUwOSwicGF0aCI6Ii82MTc4Mjg1Ni8zNTc3Mzg4ODYtYWNlZDZmYmQtMGFjNC00M2UzLTliNWMtMGU2MDY2N2FhZTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA4MzUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2OWM2ZjVkMzU2ZmFjZDVjMGY3ZDI1ZDYwNWM1ZTEyMjEzMjlmZDA2OTM5YmJhMGFjZTA3NmM5NDZiMTQ0YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tBTIbeQFoTD0RXjXINej06SXtDeFoJ-Oj8pNC2vrvJA)

data传参有问题，data必须是对象，你这里应该是传{id:1}才对
http.get('xxx', {id:1})

**Comment by Jazzzy126** [comment]
不是这个问题，我不传值也会报这个错误，已经换库了，哈哈哈
