### ISSUE TITLE
upload 并未实现

### ISSUE THREAD

**Issue by littlezo** [kviewui/lwu-request#5]
使用过程中发现，并未实现upload 接口，是否有计划支持实现呢

**Comment by lyl-code** [comment]
文档标注了未上线，参考文档：https://lwur.fdproxy.cn/api/upload.html，upload接口是有计划实现的，并且将会增加客户端OSS直传方法和相关的配置内容，应该在本周内实现上线，另外感谢支持和关注lwu-request😊

**Comment by lyl-code** [comment]
新版已支持上传下载，请查看日志：https://lwur.fdproxy.cn/changelog.html，另外感谢支持和关注lwu-request😊
