### ISSUE TITLE
小程序平台，PUT 方法非预期

### ISSUE THREAD

**Issue by littlezo** [kviewui/lwu-request#6]
小程序平台，PUT 方法非预期
<img width="657" alt="image" src="https://github.com/kviewui/lwu-request/assets/41771224/cca243b9-08f2-40c1-8576-004cc682c0b5">
<img width="832" alt="image" src="https://github.com/kviewui/lwu-request/assets/41771224/c9a41400-e92b-4221-b7e1-7bffe2a1fb91">
在小程序平台上，PUT 方法最终执行为post 方法

**Comment by lyl-code** [comment]
问题已收到，请等待回复结果，感谢关注和使用lwu-request😊

**Comment by lyl-code** [comment]
问题已定位，代码复制粘贴的时候`PUT`方法没修改`method`导致的，该问题将于下个版本修复，预计明天会发布上线，给你造成的不便请谅解，再次感谢关注和使用lwu-request😊

**Comment by lyl-code** [comment]
`1.4.11` 版本已修复，请看更新日志：https://lwur.fdproxy.cn/changelog.html
再次感谢关注和使用lwu-request😊
