### ISSUE TITLE
upload 并未实现token携带

### ISSUE THREAD

**Issue by littlezo** [kviewui/lwu-request#9]
upload 并未实现token携带，也就是说upload 还得单独维护登录态

**Comment by lyl-code** [comment]
上传下载没有继承uniapp基础请求API，所以文档中是单独的请求参数，也就没有基础请求API的特性

**Comment by lyl-code** [comment]
该问题新版已优化，更新日志：https://lwur.fdproxy.cn/changelog.html

感谢对lwu-request的持续关注与支持😊
